### ISSUE TITLE
Extracción de datos por HTTPS

### ISSUE THREAD

**Issue by CarlosTrujillo03** [luisramirez-m/mercadolibre-scrapy#2]
Cordial Saludo,

Solicito amablemente me colabores. me encuentro estancado este por este protocolo de otro proyecto.

![captura](https://user-images.githubusercontent.com/36777695/37979580-8bafdfac-31ae-11e8-84ba-72ff20142170.PNG)

No le encuentro solución tengo las siguientes configuraciones: 
Python: Version 3.6.3
Scrapy: Version 1.5.0
Pycharm Community

**Comment by luisramirezdev** [comment]
@CarlosTrujillo03 sigues con el problema?

**Comment by jirigoyen01** [comment]
Hola Luis, primero felicitarte por el video de Scrapy me ha sido de mucha ayuda. Ahora, tengo un desafio.. del siguiente portal https://www.portalinmobiliario.com/venta/departamento/las-condes-metropolitana/4075575-los-militaresnuestra-senora-del-rosario-uda?tp=2&op=1&iug=327&ca=3&ts=1&mn=1&or=&sf=0&sp=0&at=0&i=8500 hay un boton que libera los datos: "Correo" (//*[@id="lnkEmailUser"]/span) y "telefono" (//*[@id="divDatosVendedor"]/p[1]/span). ¿Como hago para que scrapy haga click en ese boton y luego extraiga esos datos?.

**Comment by jirigoyen01** [comment]
from scrapy.item import Field, Item
from scrapy.spiders import CrawlSpider, Rule
from scrapy.contrib.linkextractors.sgml import SgmlLinkExtractor
from scrapy.selector import HtmlXPathSelector
from scrapy.linkextractors import LinkExtractor
from scrapy.loader import ItemLoader
from scrapy.loader.processors import MapCompose

class CasasItem(Item):
    ubicacion = Field()
    codigo = Field()
    fecha = Field()
    valorpeso = Field()
    valoruf = Field()
    dormitorios = Field()
    banos = Field()
    superficietotal = Field()
    superficieutil = Field()
    nombre = Field()
    telefono = Field()

class CasasCrawler(CrawlSpider):
    name ="CasasCrawler"
    start_urls = ["https://www.portalinmobiliario.com/arriendo/departamento/las-condes-metropolitana?ca=3&ts=1&mn=1&or=&sf=0&sp=0&at=0&pg=1"]
    allowed_domains = ["portalinmobiliario.com"]

    rules = (
        Rule(LinkExtractor(allow = r'pg=')),
        Rule(LinkExtractor(allow = r'/arriendo/departamento/las-condes-metropolitana/'), callback = 'parse_items'),
    )

    def parse_items(self, response):
        item = ItemLoader(CasasItem(), response)
        item.add_xpath('ubicacion', '//*[@id="wrapper"]/section/div/div/div[1]/article/div/div[2]/div[2]/div[2]/div[1]/p')
        item.add_xpath('codigo', '//*[@id="wrapper"]/section/div/div/div[1]/article/div/div[2]/div[1]/div[1]/div[2]/p[1]/strong')
	item.add_xpath('fecha', '//*[@id="wrapper"]/section/div/div/div[1]/article/div/div[2]/div[1]/div[1]/div[2]/p[3]')
        item.add_xpath('valorpeso', '//*[@id="divImagenes"]/div[2]/div/p[1]')
	item.add_xpath('valoruf', '//*[@id="divImagenes"]/div[2]/div/p[2]')
        item.add_xpath('dormitorios', '///*[@id="wrapper"]/section/div/div/div[1]/article/div/div[2]/div[2]/div[2]/div[2]/p/text()[1]')
        item.add_xpath('banos', '//*[@id="wrapper"]/section/div/div/div[1]/article/div/div[2]/div[2]/div[2]/div[2]/p/text()[2]')
        item.add_xpath('superficietotal', '//*[@id="wrapper"]/section/div/div/div[1]/article/div/div[2]/div[2]/div[2]/div[3]/p/text()[2]')
        item.add_xpath('superficieutil', '//*[@id="wrapper"]/section/div/div/div[1]/article/div/div[2]/div[2]/div[2]/div[3]/p/text()[1]')
        item.add_xpath('nombre', '//*[@id="wrapper"]/section/div/div/div[1]/article/div/div[2]/div[1]/div[2]/p/span')
        item.add_xpath('telefono', '//*[@id="divDatosVendedor"]/p[1]/span')
        yield item.load_item()

**Comment by luisramirezdev** [comment]
@jirigoyen01 tendrás que usar algo como esto: https://github.com/scrapy-plugins/scrapy-splash

Nunca lo he usado, pero aquí solucionan el problema similar al tuyo: https://stackoverflow.com/questions/30345623/scraping-dynamic-content-using-python-scrapy/30378765#30378765

**Comment by luisramirezdev** [comment]
La otra manera un poco "vaga" y puede que no funcione es viendo el DOM y el Javascript, que hace esa función:

Es con este XPATH : /html/body/script[8]

Te digo manera "vaga", por que mira como es el resultado, te trae todo el Javascript, pero bueno ya podrías hacer un filtrado de información en excel o en Python.

![image](https://user-images.githubusercontent.com/25333374/40827623-6168d470-657e-11e8-998d-978cb2b22919.png)

**Comment by jirigoyen01** [comment]
Muchas Gracias Luis!, pude obtener los resultados. Ahora a pulir el codigo y seguir estudiando!. Te debo un vino Chileno haha!.

**Comment by luisramirezdev** [comment]
@jirigoyen01 Que bueno que funciono, para eso estamos. Saludos.
