### ISSUE TITLE
Problema al reconocer el comando 'crawl'

### ISSUE THREAD

**Issue by Ithalik** [luisramirez-m/mercadolibre-scrapy#3]
Buenas tardes

Estoy intentando scrapear un sitio distinto a mercadolibre.

He realizado los pasos a seguir igual que tu,pero extrapolando la información y adaptandola al sitio web que deseo scrapear.

La cuestión es que cuando le doy a ejecutar dice que scrapy no me reconoce el comando "crawl"

Estoy utilizando una instalación de python 3.6 dentro de Anaconda en su ultima version en windows 10.

Podrias ayudarme a solucionar este problema?Si necesitas que te envie los archivos de python de mi proyecto para revisar asi el posible error comunicamelo.

Muchas gracias por el Tutorial!!

Espero tu respuesta!

**Comment by Ithalik** [comment]
EL error en concreto que me da es: 

Scrapy 0.24.4 - no active project

Unknown command: crawl

Use "scrapy" to see available commands

¿Como lo soluciono?

**Comment by luisramirezdev** [comment]
Nunca he usado Anaconda, pero si instalaste scrapy? `pip install scrapy`

Dime el resultado cuando usas este comando `pip freeze --local`

**Comment by Ithalik** [comment]
Para instalar Scrapy en anaconda se usa el comando: **conda install -c conda-forge scrapy** .
Si que tengo scrapy instalado correctamente dentro de Anaconda ya que cuando llamo a scrapy me muestra los comandos que tengo activos.
El problema está en que dice que no tengo el proyecto activo y que no detecta el comando "crawl".

He intantado por tierra mar y aire hacer la intalacion de scrapy en un entorno virtual con pip como haces en el tutorial y la verdad que soy un newbie en esto y no lo consigo.
La unica forma ue he tenido de hacer funcionar algo ha sido con anaconda...y gracias a ello tengo los archivos spiders,pipelines,sttings e items modificados como necesito,pero como ya te he dicho el problema es que al ejecutar al final el programa me sale ese error.

De todas formas si me facilitas una via te envio los archivos y les puedes hechar un ojo a ver si el problema esta en ellos...

Gracias por tu respuesta.

Estamos en contacto

**Comment by luisramirezdev** [comment]
¿Pudiste ver el resultado de `pip freeze --local`?

Por otro lado, creo que tienes que crear un `env`en Anaconda, en su documentación lo dice, y después activar ese entorno virtual. 

Crear: https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands

Activar: https://conda.io/docs/user-guide/tasks/manage-environments.html#activating-an-environment

**Comment by Ithalik** [comment]
Vale,ahora ya tengo creado y activado un entorno virtual dentro de anaconda!
¿Como debo proceder a partir de aqui para que funcione la araña de scrapy?

Muchas Gracias

**Comment by luisramirezdev** [comment]
Me imagino que una vez que tengas activo el entorno, ta deberías de poder usar los comandos de Scrapy.

**Comment by luisramirezdev** [comment]
@Ithalik pudiste solucionar el problema?

**Comment by Ithalik** [comment]
@luisramirez-m Gracias por preocuparte despues de tantos dias!
La verdad es que he conseguido hacer que funcione en el entorno virtual y que no me de el error del comando crawl,ese problema esta solucionado.

El nuevo problema que tengo es que el sitio web que deseo scrapear tiene los precios ocultos para el publico y solo están visibles para los clientes con credenciales de login.

Por lo tanto,cuando scrapeo con el scrapy lo máximo que he conseguido es que me cree un csv con la referencia y la descripción de los productos,pero el precio me da error porque scrapy no puede acceder a el.

La cuestión es que he encontrado el codigo que necesito para que scrapy acceda con los datos de login aqui: https://stackoverflow.com/questions/5850755/using-scrapy-with-authenticated-logged-in-user-session

Pero no tengo ni idea de a que altura de la araña debo introducirlo o si debo crear una araña nueva.
Comentarte que yo soy un completo novato en programación y de ahi que me surjan tantos problemas.

Te agradeceria enormemente que me indicaras donde debo introducir este codigo dentro de la araña para que me scrapee el precio tambien o en su defecto si hay alguna alternativa para que funcione me la hagas saber,de todas formas creo que lo ideal seria que te adjuntara el codigo de alguna manera para que pudieras revisar que todo esta correcto.
La cuestion es que me urge mucho terminar esto y llevo mucho tiempo intentando que funcione y no lo consigo,estoy desesperado!Este es el código de mi araña:

`import scrapy
from scrapy.http import FormRequest
from scrapy.spiders import CrawlSpider,Rule
from scrapy.linkextractors import LinkExtractor
from scrapeo.items import ScrapeoItem

class scrapeoSpider(CrawlSpider):
    name = 'DScomponentes'
    allowed_domain = ['http://www.dscomponentes.es/web/']
    start_urls = ['http://www.dscomponentes.es/web/articulo/familia.php?id=79&selSubFamilia=214&selSubSubFamilia=531',
                 'http://www.dscomponentes.es/web/articulo/familia.php?id=79&selSubFamilia=214&selSubSubFamilia=533',
                 'http://www.dscomponentes.es/web/articulo/familia.php?id=79&selSubFamilia=214&selSubSubFamilia=539',
                 'http://www.dscomponentes.es/web/articulo/familia.php?id=79&selSubFamilia=214&selSubSubFamilia=540']

    def parse(self, response):
        return scrapy.FormRequest.from_response(
            response,
            formdata={'Usuario': 'dsp2010', 'Contraseña': '2010'},
            callback=self.after_login
        )

    def after_login(self, response):
        # check login succeed before going on
        if "authentication failed" in response.body:
            self.logger.error("Login failed")
            return

    rules = {

        Rule(LinkExtractor(allow=(),restrict_xpaths = ('//*[@id="principal"]/div[5]/a[6]'))),
        Rule(LinkExtractor(allow=(),restrict_xpaths = ('//div[@class="pr_referencia"]')),
                            callback='parse_item',follow=False)                      
    }

    def parse_item(self,response):
        ml_item = {}

        #Información de Producto
        ml_item['Descripción'] = response.xpath('//*[@id="descPP"]/text()').extract_first().strip()
        ml_item['Precio'] = response.xpath('//*[@id="principal"]/div[2]/div[1]/div/text()').extract_first().strip()
        ml_item['Referencia'] = response.xpath('//*[@id="principal"]/div[2]/div[4]/text()').extract_first().strip()
        yield ml_item
`

Te agradezco otra vez tu preocupación y tu apoyo!!

Saludos desde España!

**Comment by luisramirezdev** [comment]
En la documentación lo plantean de otra manera, puedes verlo aquí a lo mejor te ayuda: https://doc.scrapy.org/en/latest/topics/request-response.html?highlight=login#using-formrequest-from-response-to-simulate-a-user-login
