### ISSUE TITLE
Problema al definir Rule de paginación

### ISSUE THREAD

**Issue by kuamatzin** [luisramirez-m/mercadolibre-scrapy#4]
Que tal Luíz Ramirez, gran trabajo, me ha servido de mucho en mi trabajo, tengo una pregunta, cómo le harías para definir las Rule de paginación de la página de claroshop, por ejemplo: https://www.claroshop.com/categoria/20108/laptops/pagina/1

Existe la paginación, sin embargo no existe el atributo href en la etiqueta <a>, lo construye por javascript.

¿Hay alguna forma de hacerlo funcionar? ¿Qué estrategia utilizarías?

Gracias y excelente trabajo

**Comment by luisramirezdev** [comment]
Que tal @kuamatzin, voy a cerrar el `issue`ya que te conteste por https://www.youtube.com/watch?v=Nhk8C9JNvVw&lc=Ugwr9oJlB-cno6U5QSp4AaABAg
