### ISSUE TITLE
Es legal realizar Scrapping en Mercado Libre?

### ISSUE THREAD

**Issue by dtellogaete** [luisramirez-m/mercadolibre-scrapy#8]

**Comment by luisramirezdev** [comment]
Habrá muchas contradicciones, pero todo depende del mal uso que le puedas dar a la información. Si es una técnica no "bien vista" y hay técnicas para bloquear el Scrapping. Pero siempre habrá una manera de hacerlo, es como si tú entraras a su sitio web copias y pegas la información en un excel, pero hay scripts para automatizarlo. Aun así siempre hay unas letritas chiquitas en cada sitio web donde explican que información puedes tener y que no. En conclusión depende de ti ver si es legal o ilegal. Perdón por la tardanza pero he estado muy ocupado.
